title:             Web Transfer
email:             ranvir.singh1114@gmail.com
description:       Blog of web transfer app
author:            Ranvir Singh
baseurl:           "/webtransfer"
url:               "http://blog.webtransfer.co"

# Social Profiles
twitter_username:  
github_username:   
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
